#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  untitled.py
#
#  Copyright 2022 Diego Martinez Gutierrez <diego.martinez@ehu.eus>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
# ---------------------------
# Importación de los módulos
# ---------------------------
import random

# -------
# Clases
# -------
class NombredeClase(object):
    """docstring for NombredeClase."""

    def __init__(self, arg):
        super(NombredeClase, self).__init__()
        self.arg = arg

# ----------
# Funciones
# ----------
def NombredeFuncion(arg):
    pass

def main(args):
    Facilitador_de_mision_list = [
    'TRABAJO DE GUANTE BLANCO PARA: Instituto de investigación de Inteligencia Artificial',
    'TRABAJO DE GUANTE BLANCO PARA: Oficina del gobierno',
    'TRABAJO DE GUANTE BLANCO PARA: Hacienda',
    'TRABAJO DE GUANTE BLANCO PARA: Industria de ciberimplantes',
    'TRABAJO DE GUANTE BLANCO PARA: Fábrica de armas',
    'TRABAJO DE GUANTE BLANCO PARA: Banco',
    'TRABAJO DE GUANTE BLANCO PARA: Planta de tratamiento de residuos',
    'TRABAJO DE GUANTE BLANCO PARA: Planta de energía',
    'TRABAJO DE GUANTE BLANCO PARA: Derechos humanos',
    'TRABAJO DE GUANTE BLANCO PARA: Fabricante de medicamentos',
    'PERSONAJE SOMBRÍO: Más cromo que humano',
    'PERSONAJE SOMBRÍO: Veterano de guerra urbana',
    'PERSONAJE SOMBRÍO: Cubierto de trapos',
    'PERSONAJE SOMBRÍO: Adicto a las drogas arruinado',
    'PERSONAJE SOMBRÍO: Arma viviente (repleto de equipo, ninja, cyberfriki)',
    'PERSONAJE SOMBRÍO: Miembro de grupo terrorista anticorporaciones',
    'PERSONAJE SOMBRÍO: Espía de megacorporación',
    'PERSONAJE SOMBRÍO: Vagabundo de las tierras baldías',
    'PERSONAJE SOMBRÍO: Mutante',
    'PERSONAJE SOMBRÍO: Esquizofrénico psicótico',
    'INTELIGENCIA ARTIFICIAL: Robot de combate',
    'INTELIGENCIA ARTIFICIAL: Androide casi humano',
    'INTELIGENCIA ARTIFICIAL: Megaordenador',
    'INTELIGENCIA ARTIFICIAL: Instalación',
    'INTELIGENCIA ARTIFICIAL: Controlado por aliens',
    'INTELIGENCIA ARTIFICIAL: De la resistencia anti-megacorpopaciones',
    'INTELIGENCIA ARTIFICIAL: Subida de la consciencia de un importante profesor fallecido',
    'INTELIGENCIA ARTIFICIAL: Autoconsciente',
    'INTELIGENCIA ARTIFICIAL: Enmascarado como lo opuesto a lo que representa',
    'INTELIGENCIA ARTIFICIAL: De origen alienigena',
    'BANDA DE ROCK: Anti corporación',
    'BANDA DE ROCK: Pro corporación',
    'BANDA DE ROCK: Consume más droga que música interpreta',
    'BANDA DE ROCK: Precursor',
    'BANDA DE ROCK: Más croma que humano',
    'BANDA DE ROCK: Subterraneo',
    'BANDA DE ROCK: Extremadamente popular',
    'BANDA DE ROCK: Más dinero y fama de la que pueden manejar',
    'BANDA DE ROCK: Banda de un solo hombre',
    'BANDA DE ROCK: Hologramas programados y computerizados y generador de música aleatorio',
    'HACKER, QUIÉN ES: 24/7 conectado y iviendo en el cyberspacio',
    'HACKER, QUIÉN ES: Miembro de un culto del ciberespacio',
    'HACKER, QUIÉN ES: Tiene rarezas, raros hábitos',
    'HACKER, QUIÉN ES: Paralizado de cuello abajo',
    'HACKER, QUIÉN ES: Abuso de droga experimental',
    'HACKER, QUIÉN ES: Famoso',
    'HACKER, QUIÉN ES: Solo un crío',
    'HACKER, QUIÉN ES: Cautivo en el ciberespacio',
    'HACKER, QUIÉN ES: Usa warez y equipo de la vieja escuela',
    'HACKER, QUIÉN ES: Operar desde el espacio',
    'StreetSecurityMilitia (SSM): Luchan contra delitos callejeros',
    'StreetSecurityMilitia (SSM): Aceptar soborno',
    'StreetSecurityMilitia (SSM): No hacen nada importante',
    'StreetSecurityMilitia (SSM): Corrupto',
    'StreetSecurityMilitia (SSM): Consta de ciudadanos preocupados',
    'StreetSecurityMilitia (SSM): Veterinarios que abusan de drogas',
    'StreetSecurityMilitia (SSM): Más cromo que humano',
    'StreetSecurityMilitia (SSM): Gatillo fácil',
    'StreetSecurityMilitia (SSM): Demasiado tímido para actuar',
    'StreetSecurityMilitia (SSM): Lucha contra megacorporación',
    'MEGACORPORACIÓN: Uno de los mayores fabricantes de medicamentos experimentales',
    'MEGACORPORACIÓN: Experimentan en humanos',
    'MEGACORPORACIÓN: Violan los derechos humanos',
    'MEGACORPORACIÓN: Precursor de I.A.',
    'MEGACORPORACIÓN: Más poder armamentístico que otra cosa',
    'MEGACORPORACIÓN: Despiadados que hacen todo lo que necesitan sin miramientos',
    'MEGACORPORACIÓN: Fabricación vehículos de lujo',
    'MEGACORPORACIÓN: Cibernética, armas, armaduras móviles...',
    'MEGACORPORACIÓN: Nadie sabe que hacen realmente',
    'MEGACORPORACIÓN: Opera desde una estación espacial',
    'DETECTIVE/OJO PRIVADO: Viejo borracho',
    'DETECTIVE/OJO PRIVADO: Sólo hace casos menores',
    'DETECTIVE/OJO PRIVADO: Perdió a su familia, extremadamente vengativo',
    'DETECTIVE/OJO PRIVADO: Loco de remate',
    'DETECTIVE/OJO PRIVADO: Por dinero lo que sea',
    'DETECTIVE/OJO PRIVADO: No se entera de lo que pasa',
    'DETECTIVE/OJO PRIVADO: En la nomina de una megacorporación',
    'DETECTIVE/OJO PRIVADO: Se esfuerza por ser un buen tío',
    'DETECTIVE/OJO PRIVADO: Usa pistolas antiguas',
    'DETECTIVE/OJO PRIVADO: Siempre fuma un cigarrillo, siempre',
    'REPORTERO/PRESENTADOR: Fácil de sobornar para que cuente una historia diferente',
    'REPORTERO/PRESENTADOR: Tras la verdad pese a su propia seguridad',
    'REPORTERO/PRESENTADOR: Canal privado subterráneo',
    'REPORTERO/PRESENTADOR: Tiene secretos sucios en la manga por si acaso',
    'REPORTERO/PRESENTADOR: Tiene pequeño ejercito personal para protegerse de sus tareas',
    'REPORTERO/PRESENTADOR: Nadie se preocupa de sus informes, es una bomba rubia alucinante',
    'REPORTERO/PRESENTADOR: Opera fuera de la ciudad',
    'REPORTERO/PRESENTADOR: Ha perdido la memoria, vive el momento y lo relata',
    'REPORTERO/PRESENTADOR: Debe toneladas de dinero por material que ha obtenido de fuentes privadas',
    'REPORTERO/PRESENTADOR: Es un espía de un estado extranjero',
    'MIEMBRO DE UNA BANDA: Cartel de la droga',
    'MIEMBRO DE UNA BANDA: Trata de blancas y prostitución',
    'MIEMBRO DE UNA BANDA: Armas',
    'MIEMBRO DE UNA BANDA: Vandalismo, travesuras, desobediencia civil, anarquía',
    'MIEMBRO DE UNA BANDA: Propaganda anticorporativa',
    'MIEMBRO DE UNA BANDA: Matones',
    'MIEMBRO DE UNA BANDA: Mafia corporativa',
    'MIEMBRO DE UNA BANDA: Psicópatas cibernéticos',
    'MIEMBRO DE UNA BANDA: Intrusos',
    'MIEMBRO DE UNA BANDA: Hackers'
    ]
    Tipo_de_mision_list = [
    'PROTEGER: Inteligencia',
    'PROTEGER: Escondite anarquista',
    'PROTEGER: Vivienda',
    'PROTEGER: Banda de rock',
    'PROTEGER: Planta de energia',
    'PROTEGER: Tú mismo/ tu banda',
    'PROTEGER: Individuo anticorporación',
    'PROTEGER: Niño mutante biomecánico',
    'PROTEGER: Tecnología cibernética',
    'PROTEGER: Ruta de datos secreta de un netrunner',
    'INTELIGENCIA DE: Sede megacorporación',
    'INTELIGENCIA DE: Oficial corrupto',
    'INTELIGENCIA DE: Planes de una I.A.',
    'INTELIGENCIA DE: Nueva droga peligrosa',
    'INTELIGENCIA DE: Guerra entre anarquistas y megacorporaciones',
    'INTELIGENCIA DE: Viejas alcantarillas',
    'INTELIGENCIA DE: Ático de palacio celestial',
    'INTELIGENCIA DE: Motivos del canal de noticias',
    'INTELIGENCIA DE: Banda de rock',
    'INTELIGENCIA DE: Hacker',
    'ANIQUILACIÓN: Jefe Megacorp',
    'ANIQUILACIÓN: Más cromo que humano enloquecido y berserk',
    'ANIQUILACIÓN: Sede Megacorp',
    'ANIQUILACIÓN: Hacker arruinando el sistema para todos y todo',
    'ANIQUILACIÓN: Planta de energía para sector rico',
    'ANIQUILACIÓN: Reportero Promegacorp',
    'ANIQUILACIÓN: Banda de rock Promegacorp',
    'ANIQUILACIÓN: Fabrica de drogas peligrosas',
    'ANIQUILACIÓN: La policia de la zona',
    'ANIQUILACIÓN: Satélite del espacio exterior',
    'EL HURTO: Un montón de drogas',
    'EL HURTO: Datos musicales de una banda',
    'EL HURTO: Un montón de armas',
    'EL HURTO: Documentos megacorporativos',
    'EL HURTO: Cibertecnología experimental',
    'EL HURTO: Productos alimenticios',
    'EL HURTO: Secuestrar una persona',
    'EL HURTO: Planes de megacorporación',
    'EL HURTO: Un montón de dinero',
    'EL HURTO: Ciberdatos',
    'RECUPERAR: Datos',
    'RECUPERAR: Drogas',
    'RECUPERAR: Dinero',
    'RECUPERAR: Gente',
    'RECUPERAR: Armas',
    'RECUPERAR: Vehiculos',
    'RECUPERAR: Planos',
    'RECUPERAR: Información de inteligencia',
    'RECUPERAR: Equipamiento',
    'RECUPERAR: Cibernética',
    'RESCATAR: Anarquista',
    'RESCATAR: Niño/a',
    'RESCATAR: Inteligencia Artificial',
    'RESCATAR: Miembro de la familia',
    'RESCATAR: Inocente',
    'RESCATAR: Jefe de megacorporación',
    'RESCATAR: Químico de drogas experimentales',
    'RESCATAR: Señor del crimen',
    'RESCATAR: Oficial de la milicia',
    'RESCATAR: Hacker',
    'COMPRA-VENTA (50/50): Drogas',
    'COMPRA-VENTA (50/50): Armas',
    'COMPRA-VENTA (50/50): Cyberware',
    'COMPRA-VENTA (50/50): Vehículos',
    'COMPRA-VENTA (50/50): Intel',
    'COMPRA-VENTA (50/50): Planos',
    'COMPRA-VENTA (50/50): Gente',
    'COMPRA-VENTA (50/50): Edificios',
    'COMPRA-VENTA (50/50): Zumo de mutación biológica experimental',
    'COMPRA-VENTA (50/50): Libertad',
    'CAPTURAR: Miembro banda de rock',
    'CAPTURAR: Jefe megacorporativo',
    'CAPTURAR: I.A.',
    'CAPTURAR: Sede central megacorporativa',
    'CAPTURAR: Sección del ciberespacio',
    'CAPTURAR: Calles',
    'CAPTURAR: Departamento miliciano',
    'CAPTURAR: Traficante callejero',
    'CAPTURAR: Satélite en órbita',
    'CAPTURAR: Ciberfriki',
    'OCULTAR: Información privilegiada',
    'OCULTAR: Jefe anarquista',
    'OCULTAR: Reportero en problemas',
    'OCULTAR: Mercancías ilegales',
    'OCULTAR: Vehículo',
    'OCULTAR: Localización de los escáners de la milicia',
    'OCULTAR: Tu propia cibernética',
    'OCULTAR: Niños que se planea capturar para trabajar en centrales eléctricas',
    'OCULTAR: Una I.A. que a traicionado a una megacorporación',
    'OCULTAR: ¡Tú mismo!',
    'PROTEGER: Tu propio bloque',
    'PROTEGER: Reportero en una misión arriesgada',
    'PROTEGER: Anarquista que quiere atentar contra una megacorporación',
    'PROTEGER: Esquina privada de matones',
    'PROTEGER: Contrabandista que trafica para los pobres',
    'PROTEGER: Hacker pirateando archivos de una megacorporación',
    'PROTEGER: Planta de energía objetivo de anarquistas',
    'PROTEGER: Gente de la milicia',
    'PROTEGER: Raro animal vivo',
    'PROTEGER: Satélite en órbita terrestre. Quieren destruirlo para que no emita publicidad anticorporativa.'
    ]
    Objetivo_list = [
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'LOCALIZACIÓN: 'Localizacion_list,
    'PERSONA: 'Facilitador_de_mision_list,
    'PERSONA: 'Facilitador_de_mision_list,
    'PERSONA: 'Facilitador_de_mision_list,
    'PERSONA: 'Profesiones_list,
    'PERSONA: 'Profesiones_list,
    'PERSONA: 'Profesiones_list,
    'PERSONA: 'Antagonistas_list,
    'PERSONA: 'Antagonistas_list,
    'PERSONA: 'Antagonistas_list,
    'PERSONA: 'dos_objetivos,
    'MEGACORPORACONES: Sokotyo – fabricante de electrónica de consumo de alta calidad (y secretamente adictiva)',
    'MEGACORPORACONES: V3 – centro recreativo de realidad virtual',
    'MEGACORPORACONES: WarLogic – desarrollo de nuevo equipamiento militar y armamento',
    'MEGACORPORACONES: Somotholos – imperio drogas',
    'MEGACORPORACONES: Neotime Pops – clubs y entretenimientos',
    'MEGACORPORACONES: Panzerfist – deportes de combate y entrenamiento, secretamente trafico humano',
    'MEGACORPORACONES: Andromeda666 – tecnología espacial',
    'MEGACORPORACONES: Victory-10 – clase baja opresora intentando limpiarlos por cualquier medio',
    'MEGACORPORACONES: Satin XXX – estimulación sexual',
    'MEGACORPORACONES: !FutureNow! - investigación biomecánica, experimentos humanos, mutaciones, manipulación genética',
    'INTELIGENCIA: Archivos que prueban que una megacorporación usa humanos para experimentar con ciberimplantes',
    'INTELIGENCIA: Protocolo seguridad ciberespacial',
    'INTELIGENCIA: Planos de puntos estratégicos importantes de la ciudad para los anarquistas',
    'INTELIGENCIA: Datos de una tribu del páramo',
    'INTELIGENCIA: Fuentes para canal de noticias',
    'INTELIGENCIA: Documentos que muestran como la milicia blanquea el dinero',
    'INTELIGENCIA: Localización del paradero de una organización criminal',
    'INTELIGENCIA: Localización de la casa del CEO de una megacorporación',
    'INTELIGENCIA: La fórmula especial de la fabricación de medicamentos para el encantamiento de la mente y el cuerpo',
    'INTELIGENCIA: Coordenadas del satélite espía',
    'OBJETO: Mano cibernética dorada y cubierta de diamantes. Lastima que esté unida a alguien',
    'OBJETO: La mejor plataforma informática de la ciudad',
    'OBJETO: Un cajón con armas grandes',
    'OBJETO: Fabrica portable de drogas',
    'OBJETO: Ingredientes para explosivos caseros',
    'OBJETO: Piezas de tuning lujosas para vehículos',
    'OBJETO: Una ciberllave que abrirá cualquier cerradura, mecánica o digital',
    'OBJETO: Objectos de arte',
    'OBJETO: Servidor de megacorporación',
    'OBJETO: Basura cara caída del espacio',
    'DATOS (50/50 DL O ELIMINADOS): Secretos sucios de un CEO megacorporativo EO',
    'DATOS (50/50 DL O ELIMINADOS): 10.000.000 creditos virtuales',
    'DATOS (50/50 DL O ELIMINADOS): Futuras noticias aun no admitidas',
    'DATOS (50/50 DL O ELIMINADOS): Protocolo seguridad militar',
    'DATOS (50/50 DL O ELIMINADOS): Software para controlar los robots de la milicia',
    'DATOS (50/50 DL O ELIMINADOS): Localización de bienes ilegales y robados en mapa virtual',
    'DATOS (50/50 DL O ELIMINADOS): Información GPS de un escondite anarquista',
    'DATOS (50/50 DL O ELIMINADOS): Futuros planos de la ciudad',
    'DATOS (50/50 DL O ELIMINADOS): Votaciones de concejales',
    'DATOS (50/50 DL O ELIMINADOS): LA VERDAD',
    'TECNOLOGÍA AVANZADA: Teleportador personal, necesita un marcado activo de destinación',
    'TECNOLOGÍA AVANZADA: Arnés, cuando se coloque modificará las capacidades y habilidades físicas humanas en un 50%, pero matará al sujeto si se lo quita. Lentamente degenerará al sujeto en letargo, donde será controlado como un robot por «Lanza en c-3»',
    'TECNOLOGÍA AVANZADA: Traje antigravedad. ¡Te hace flotar como si no hubiera!',
    'TECNOLOGÍA AVANZADA: Gafas de rayos X. Tres intensidades: 1-ver a través de a ropa, 2-ver a través de las paredes, 3-ver las líneas del ciberespacio en el aire',
    'TECNOLOGÍA AVANZADA: Batería infinita. Se puede colocar en cualquier dispositivo, pero cuando se coloca, se funde en él y no se puede quitar sin dañarlo y destruyendo la batería',
    'TECNOLOGÍA AVANZADA: Generador de números aleatorios. Genera entre 1 e ∞',
    'TECNOLOGÍA AVANZADA: Tanque de batalla de alta tecnología',
    'TECNOLOGÍA AVANZADA: Guante multiherramienta portátil',
    'TECNOLOGÍA AVANZADA: Sistema auto objetivo militar con efectos de mejora de la visión de lujo',
    'TECNOLOGÍA AVANZADA: Alguna tecnología alíen... nadie sabe que hace ¡todavía!',
    'CAMPAÑA POLÍTICA: Idealistas antitecnología',
    'CAMPAÑA POLÍTICA: Candidato corrupto',
    'CAMPAÑA POLÍTICA: Partido supremacista humano aumentado',
    'CAMPAÑA POLÍTICA: Nuevo partido populista linchando al actual consejo',
    'CAMPAÑA POLÍTICA: CEO megacorporativo apoya la ley marcial',
    'CAMPAÑA POLÍTICA: Activistas hackers',
    'CAMPAÑA POLÍTICA: Pacifistas cabezacromo',
    'CAMPAÑA POLÍTICA: Gente contra crueldad robot',
    'CAMPAÑA POLÍTICA: Salvadores medio ambiente',
    'CAMPAÑA POLÍTICA: Culto al salvador',
    'FIESTAS: Orgía sexual de neón',
    'FIESTAS: Rave de éxtasis',
    'FIESTAS: Caos en ciberespacio',
    'FIESTAS: Estricto código de vestimenta',
    'FIESTAS: Carnaval de la Tomatina',
    'FIESTAS: Quedada joven corporación',
    'FIESTAS: Mosh Pit/muro de la muerte',
    'FIESTAS: Boda',
    'FIESTAS: Foso animal (sorteo, alcohol, drogas, boxeo, todas las cosas desagradables)',
    'FIESTAS: Convenio',
    'EXTRAÑO: Envío de conejitos rosas de peluche'
    'EXTRAÑO: Cajón lleno de extraños y horrorosos juguetes sexuales'
    'EXTRAÑO: Caja llena de holodiscos piratas de conciertos de rock grabados ilegalmente'
    'EXTRAÑO: Bola de cristal que es una cyberdeck estilizada'
    'EXTRAÑO: Tubo enorme con un hibrido de humano y alíen en el interior'
    'EXTRAÑO: Impresora de tarjetas de crédito falsas (recargada)'
    'EXTRAÑO: Surtido de disfraces para Halloween'
    'EXTRAÑO: Llantas de coche brilli-brilli'
    'EXTRAÑO: Carne de unicornio en lata'
    'EXTRAÑO: Documentación completa de propiedad megacorporativa ¡No has de poseer nada ni montar un negocio para ser una megacorporación!'
    ]
    En_posesion_de_list = [
    'DESCONOCIDO: [tabla a, e, g]',
    'ROBADO: [tabla f]',
    'MEGACORPORACIÓN: [tabla c-3]',
    'PANDILLA: Ciclistas',
    'PANDILLA: Yonquis',
    'PANDILLA: Músculos de cromo',
    'PANDILLA: Mega modernos',
    'PANDILLA: Hippies ácidos',
    'PANDILLA: Anarquistas',
    'PANDILLA: Mafia',
    'PANDILLA: Matones Mendigos Unidos',
    'PANDILLA: Grupis de banda de rock',
    'PANDILLA: Hackers',
    'SEGURO: Búnquer con sistema de cierre mecánico complejo',
    'SEGURO: Búnquer con cierre complejo virtual y digital con peligrosos programas defensivos',
    'SEGURO: Vigilado por una torreta',
    'SEGURO: Vigilado por mercaderes',
    'SEGURO: Detrás una red láser',
    'SEGURO: Oculto detrás de una puerta/escotilla secreta',
    'SEGURO: Camuflado',
    'SEGURO: En otro lugar [tabla f]',
    'SEGURO: Artículo falsificado, original en otro lugar [tabla f,d]',
    'SEGURO: Estación espacial',
    'COMÚN: Familia normal',
    'COMÚN: Colega que se relaja escuchando música en unos grandes auriculares',
    'COMÚN: Desempleado',
    'COMÚN: Dueño de una tienda',
    'COMÚN: Distribuidor recambios (legal)',
    'COMÚN: Alguien que quiere pasar desapercibido, masa social',
    'COMÚN: Taxista',
    'COMÚN: Limpia ventanas rascacielos – tiene una tienda de campaña en la plataforma donde trabaja. Coste eficiente',
    'COMÚN: Basurero',
    'COMÚN: Niño o niña',
    Facilitador_de_mision_list,
    Profesiones_list,
    Antagonistas_list,
    'EL PROPIO DONANTE DE MISIÓN'
    ]
    Profesiones_list = [
    'GUERRERO CALLEJERO: ',
    'ROCKSTAR: ',
    'GUANTE BLANCO: ',
    'MERCENARIO: ',
    'PERIODISTA: ',
    'PROFESIONALES INFORMÁTICOS: ',
    'OPERARIOS: ',
    'BAJOS FONDOS: ',
    'PERSONAL MEGACORPORATIVO: ',
    'RAROS: '
    ]
    Localizacion_list = [
    'CALLES: ',
    'SEDE DE MEGACORPORACIÓN: ',
    'BAJO TIERRA/MAZMORRAS: ',
    'CLUB: ',
    'ALMACENAJE: ',
    'PUBLICO: ',
    'SERVICIOS ESPECIALES: ',
    'SILVESTRES: ',
    'CENTRO DE INVESTIGACIÓN: ',
    'ESTACIÓN ESPACIAL: '
    ]
    Antagonistas_list = [
    'SUPER A.I. SE HA REBELADO',
    'LÍDER DE UNA BANDA CON CROMO Y ESTEROIDES',
    'DRON DE SEGURIDAD CON LASER AMETRALLADORA CON MIRILLA Y ALGUNOS MICRO-MISILES',
    'CLÁSICO SICARIO CON TRAJE Y ARMAMENTO OCULTO Y CON SILENCAIDOR',
    'MERCENARIO VETERANO QUE SABE LO QUE HACE, Y MUCHO MÁS',
    'JEFE CORPORATIVO QUE QUIERE MATAR A TODOS LOS DEMAS JEFES PARA DIRIGIR TODOS LOS NEGOCIOS',
    'VAGABUNDO CON UN EJERCITO RATAS CIBERNÉTICAS DE CHATARRA',
    'POLÍTICO ANARQUISTA MUY QUERIDO QUE TIENE AL PUEBLO DE SU LADO',
    'ABOMINACIÓN MUTANTE CON BABA ÁCIDA, FUERZA COMO DE 10 HOMBRES Y PODERES PSÍQUICOS. ¿ME OLVIDO ALGO?',
    'EL PRESIDENTE DE LA SUPER NACIÓN COMUNISTA DEL ESTE'
    ]
    Premios_list = [
    'INTELIGENCIA',
    'OBJETO',
    'DATOS',
    'CREDITOS',
    'PISTOLAS & ARMAS:',
    'CIBERTECNOLOGÍA: ',
    'ALIADO PODEROSO; ',
    'REPUTACIÓN: ',
    'TRAICIÓN: ',
    'MUERTE (O BUENO, CASI): '
    ]
    Evento_Aleatorio_list = [
    'Tabla a: ',
    'Tabla b: ',
    'Tabla c: '
    ]
    Trabajo = random.choice(Facilitador_de_mision_list)
    Mision = random.choice(Tipo_de_mision_list)
    print (Trabajo+' quiere '+Mision)
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
